version: '3'
services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "4000:8080"
    volumes:
      - /mnt/docker/open-webui:/app/backend/data
