version: "3"

services:
    client:
        image: nginx
        ports:
            - 8000:80
        volumes:
            - nginx:/usr/share/nginx
            
nginx:
  homebridge:
    external: true
    name: "nginx"        
