version: "3"

services:
    nginx:
        image: nginx
        ports:
            - 80:80
        volumes:
            - nginx:/usr/share/nginx
            
volumes:
  nginx:
    external: true
    name: "nginx"        
