version: "3"

networks:
  gitea:
    external: false

services:
  gitea:
    image: gitea/gitea:1.21.3
    container_name: gitea
    environment:
      - USER_UID=1030
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - /mnt/docker/gitea/data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
