version: "3"
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    user: 1030:100
    ports:
      - "4533:4533"
    restart: unless-stopped
    volumes:
      - "/mnt/navidrome/data:/data"
      - "/mnt/music/:/music:ro"
