version: "3"

services:
    nginx:
        image: nginx
        network_mode: host
        volumes:
            - nginx:/usr/share/nginx
            
volumes:
  nginx:
    external: true
    name: "nginx"        
